language: go
go:
- '1.5'
- '1.6'
services:
- docker
env:
  matrix:
  - REPO=quay.io/wantedly/kong-oauth-token-generator
  global:
  - secure: YvxJJU6v5lEcdO7q8PukQvQbvfUVqUWcsVVABYx+8Dkiezzpn9qSz2GdlchcbsY5k5PBueoe60saESSGDZadPStubUy0EsTCdcAvkCtLEFnuF0+LldRcZ55bmxsmsChK96aX9d/1Q+9fVnUroiR7P3x6OZtb9Vlmmogz8x9PoEWgD3ncl6D9kpOp5+yID9dz2q5WvTBGGIqdgmBjlDu+GZXjOakbN8eF3yjGosC/2ah+6daM5nWeFNSVQbvMbxot+VGDUyCLTww0ekTEOTO2vxH2vfje2F/0gziQBOKnQ7IDfm0pSExhl1oT0CEPg7Zdxcyg6YepqvLYhhdis5pUJvi/o//aYLJudKv5nNpJ74xTXqxbROMCC2NU+J2GpqE3WuQ030XAqUlacfgwe/NpAlmkjXYqm6XaOmPZUiZyyv+f3qKnlNndWMwzL7ZMbWFBmzoVVAjESs3GRjKaq8r2j2/07Eu8AyxNQs7vBaSnNtWPM9Pqwtu7Yuwi25oNEH1x1J+jf1AhknWJMrxPGmOvy3J1gWT1gB5w7HPNDFjb9bHQrqXdoAvKNqZn7oHE1sif6ocNG7FtiXyATTRRUN4AHMak3N/TmBrwsUjs4rf2CLrrHP90pq5Aesigc6pvZUnmChkewi19KQdZlkCiguVDIk4Ax57Xv20X7m5qCr/Yr8E=
  - secure: PE6HxgIt6dZAofRiKsAvEZbaksW1wM1TbdWZJBIY9ipUqE8wpQBS6q+ZLa3HiBNtLAC3sFREuPhoz8OsFSNyH/0xeZzbaJi6eJ3CaLwgZ3UG/SjP4wdckiMZ1aCm/XjtNK6TfvhrLIh5gFjpvdSv0BAsNat8Y+STPpCCYbae4pvvs84OAtzh8Fs1CqzrtPHFBkeL7pxfJgkm8hnC/Pnxrn2diWkuRdX9ozNohFRsdlGPGOLHSJ3DndIZgb4q6SrnuKKLp2Wjuw1/6y/vVY5Gd2W9mVcaULPM8iyPOxL9JlkQgKXdvXEP8lQp99OVO1S3rcv1AcOJxhssq+seHj1u8tdePHx+zOQTw8v2Ea7u+2eyawDxn2YmAuN9PnKGhg7TMMP6uI2K2QH5KS0myvcrBswWwBEClOsPWn+sjxx7Tb5luEOeaiU9P5Wzu+yPdocBTA3Hn2fieekwe+NR4IU0Jh15aUYVJO5ieyZKQqEQxtoUu2pPcXvbgBg+KTLDftsGyZ+XQc/46FpuC5xoSwbovALUKQGRpya4w6vwyp+LmW6SgCqu6UF5Fx0uUODcWFyXwF+8DRwcQGTiFP4+cZ7pP0FCk6xW2MrQG98Dh9Rqc0XYpEwUuOHBRdR1MX86yHrMAlY483cN4cVax+w93v6gFoKMMV/VtB1llG3bF8D2o/E=
  - secure: yYRmtu+ua7FpsweZJ74yeRCeDfgGh42g6ANC2uNYjzL/LEczNEdoxrafoKza7tMvi221lk0IahiRq8012jjcSapf2CbsthxJYjkrnIUZx2eF5ftl5ogD9JTR5140W2yzWj6dKsnOJOGxNFkzmDkwm08k9St/qmr4iVJKRUlBjL0s8tsTRrLBCyICss4XLuqXx/abiXcECsAgXo6kvCgzBLRtiat44gd3HJizduPHFDXe6UoNLwyznQQFyIBnrxu82fvNs4xhva39idA0goDtm1C9yiNnBSPDNBx9YgdjvBE+WonmaFW9HPTFawL4sMvgHYgcNhICyVsdfcFsDp/MKfTYe0Il+pPpwHE8eBklTbHbAQmeUWQ0OWOKbmI7i8jrH/vND+wfUK9DkvI8tQa6XbXhBvnsxArknp8/8sAmJdwM+QyYTt7wD27mB0fnJlJM0eKGqqPGY3SPvHguW4sKl2WGnKprEusOmSehEqzBvOWHE/u5iFdH5hqe2kAeZ1s3ZjdfeUxVYQOHQymS9pt5W7SBPZwmTD7nJKFm1gR+4AmGD+UX60XmdDbSbSGFubYS8Jt74EoQNS3d6KqLfDrcHq68JurN9wLAwHXz5RJhodmlyn0qrAtX57blTdJQF7GzBHzdDX3GrRJl4CUg/1tb7YAPqsFSpiM6KrmmAKFWXGs=
script:
- echo ${TRAVIS_COMMIT::8}
after_success:
- export BRANCH=$(echo $TRAVIS_BRANCH | sed -e "s,/,_,g;")
- export TAG=$BRANCH-${TRAVIS_COMMIT::8}
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io
- docker pull $REPO
- echo "docker build -t $REPO:$TAG ."
- docker build -t $REPO:$TAG .
- echo "docker push $REPO:$TAG"
- docker push $REPO:$TAG
