language: go
go:
- '1.5'
- '1.6'
services:
- docker
env:
  matrix:
  - REPO=quay.io/wantedly/kong-oauth-token-generator
  global:
  - secure: D+Co8+pSduDXVqJ/XJ7UqkmjP+8mdfuigulAxJewTY24bUuQSwE12Zm+bl3KR3nY4gox7kAlWC7/LMNDBO6uHNncbj8vQnItVZwxl49XfalfJ2v7L2zZouHSQnYQQwWLSjyXqYi9tRY9G9PsJMX/tTiE8Gru6X+OtbsbjKJd/0wJ6yeIX/7Qc3+haJTCCFSFAQTF+1dVL5lx3h1GXTB4k9czL5piM6YIpvmwC0Y6ECbDRGUF6RZV6IVsPzu8g8PXNKTqGADbCTb3dNVUwTMc/4EGyVVGmeqc6DrH29pQTYB7R37MsNjJJFe3Aus6agvq/RscRkfM3wsepHy+PRba/f/PIlutWumt9n0tXLTjB+7uYEe0EJ3ut0Gz2dLURp/catfI+nGIGqxZt7PvTYYaowhdQIzRnxRW10Qx/0TSOfZCPSV+P1PWod4gPQCmPkZT+7o20c3L399cse1aG5setn3FVKgvX1V05wzzDDAwuAUQDsti/yNn6vMn+lPWP1FjiomFQcZPMSk1iOvmOWh5vebW0u8R5F/PqeKTY0txJSGijL93WG1FOnqRltUoHhgy+GEAMynBQgVvRG1OQrBtIl0fhsx5OAA9dC+PNbSSws54k/pNPALuuIRmAosxlHd5ixOdMgJP415OEppkQ4zr1991ITksouVp+58SKD/8GMA=
  - secure: rdBv7TDqAH+pRcppt93QOT/wqiHLGkoA2Ye9Txoki2BC4O2yhcYNIkpJF387fkyWCHnfqq2LMQst77TKTaQIOBIJ9Y8qTwaY1+XPtkWBUJeXLDW2N5irk1eJIpVLjwc2PBTAPzvM07O9/wzaiaHuaydvweXeJ3d45uK1cRMxgnhM+KhyHPSsTPSv1S1mkILMJq52+rFPh2ESHkwNhPWF5Dw2ILGnfhbkNI+GM7P9RS+UOpKVD5FxWDS9mynQQHnXh1nIc9Y8s9K+BgkiylZ8IQ28fXOq7X84DC/eJ7SZaYXq/pUV6iR5JTDVTGE/7B5gHv7Fo4FXa/UEbzpxtQ9x0B+wkZ71t02uceWRRZ4kXjrKu8PwJZCEChn5onO1TV9L4bfDWeEIDOSeZxaWIFwUk6RULrU7m1j4ZGu6Q3gZi4d0BE3AyiABktYtT6MFN0+vm4QfMciTl0UREgcHjWXIGC3bwYcSGbiB+8ktt3C6DrEr6gjlom2RkWhym/CBXs46Fv0S0Z7P99czqhYk2NZ2ohUKMIWhlREKoawDp/CqLrflFwUKONVWkibjKk9koqjMotJyoJUXYtEBHTUWillohQImww9Cgt1F0wsoV/7GAQKevy0XInyHiVAOQfW2BWIifE32UUZpzMdO9Qrv7dXF60ifzzNO6mfdr8DgFBhk4t0=
  - secure: q44XyHjbu6+tyu3kaOwqL0xyos1v4L2rHncuHE+FzT2EHC4S2C4W8lgr7Cx9IDuTNwMiEJM3dP341vEho3i0OV3q51pgf3Dc51RNP9N3e3qHBID08p7SRBjS/sw2PtUPmtN3CjNQ5Yns4K7ZXzAfOZMh1p4+VOQohAnljz9pRH8GSHRx2/AMNsGCoXc/FXSSbroMqIjDxHlMQbTN6qouSIAq5z//prUUKlcEsxoo+yec0fYA98lqr0N81A736T6QopTdsQe6X1ffz79Ou6DJXhZkZzNruQkAkQKcO7+eg0V24SS2fdtxEuw07ZAqx+Rq8SFCn0gfoJCHsb0MswWv4af6c39EWqa0AQKh76tKQ/TI8zo0LCfZFmDzFVa5aDqa8No1JqK5o8qmHsCzStTbmTnejtmFNaYnejGpbmAJhpwAWqV+iu9BA17ogHnlz62h1oLDCTZOR6JZuFtGq8fNyVPbixFP6zpItrmKOSAbhtmE1EONqYAe7LviSkaOVA4UONOarz1E1bOo1indwcnhIPQ5p3Hy0AGfg6LNgW/2R70WbuOUll4mTyTAQYtZ90zqE9kTymxuFNwMm44H1AU1wm3Ey1xz1FeBKGcGjZxSa2XzRwi+KmgcoARI12inIUefpfeilnZ/iThEOeFeul5I0SHv5gKQnMLZ0SuWAtB55Cs=
script:
- echo ${TRAVIS_COMMIT::8}
after_success:
- export BRANCH=$(echo $TRAVIS_BRANCH | sed -e "s,/,_,g;")
- export TAG=$BRANCH-${TRAVIS_COMMIT::8}
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io
- docker pull $REPO
- echo "docker build -t $REPO:$TAG ."
- docker build -t $REPO:$TAG .
- echo "docker push $REPO:$TAG"
- docker push $REPO:$TAG
