language: go
go:
- '1.6'
services:
- docker
env:
  matrix:
  - REPO=quay.io/wantedly/kong-frontend
  global:
  - secure: W6dSkcoetkqoEEmZHfAndRCeaxYE+sl99abIOFFNXWQDptnaMaqZORHdAxpTmLKFMSFD84ns3f6z/wGeuMCFjfKxs2FGsMPYgqMgN3diDD/Yzqzdg/m1zDG/S6QU8dB+ZT4wJyr5bY7fu2qNk6CGcGBkrbIiaD0eWXfxa+/6RSOfbfWLd4KWaPZcD5JBbrFn5pRHdO2Ps8mhVI5UbILugKOjor/UFt2eNSexlSUU/srvZjMA/OokY7TJ+gPCagUGtqHXaNHjgg/B9aAiA5HkXa8Td+Y10iUfBiYe14e6GkaDUatBmbCHuTrQKRXSUpWmBGiaMVaTxX1XDDdoXam5+4V4kvQgPmFw+Ha9BxPwY9mOweDJcqjPlCHuW+OI/uH0z/l/3kx82TnDaHNtsrkciM+GXxypXsb84GipErR64rLIoIMLjOU4c9X986FR1Yt2Ti2gxuL8DIGeyuEkDO03DtxF77k0ujtkNtDX+IWoR2x0n1lG2UYHXq2k0qeusuxrw56JU3YEv38iFfEK+WNQQ46oljUjUpiqwtBr/Nuov+4ALhQgGyjpLHm2VPIEt3lvRmkqcq1uRqFgjJDowhM/Pdz+VW4mHKHqmcE1GafH5G+md1KTSEawHAccP40oS+aRebMFEVcy3nJsWw4+RF5m/bMJE6PAXFRk7tN/4X/UZdU=
  - secure: xwo1JcJEF7YXlKKswy4vSWOTJV0k+wgRLP2p8GG2wQQrdDqtHbEMAbHPYJFfdgFtHfeHxoNmgX4tlrvxhm/Xav/ISbFCRXhstLKyrTfSczqC0/QEfRuLgI1xK3KmUVLmC2fh5u/Ai4ARF9bDALj8ErHpx8P7LjnP/WwzdAD7YLIZhstJhsarLw8Jqj2YMpnPwoADYcOdZwfyS8EUQ8jzZmLDgZCRATR3vAWXEGeiOIowbioFFAIW0eczK5ibMRTLd1jDSrYc7TFp7phYmsZdyi31fLfmI72gIYnFWA7+vEAxfFOFA3LoxjEAUfvzoslUsLK/MSCztrgCx4l/nh/kjwe9D4rDRoOmePNw4oTgUZ01l2wKjwXBjL7JJwEFndvl1cHLgEQsXBKNM/p3pBe08fNjaJoWlT7qrzjHF7h9MR01hl4bprp3XwK9PU5SgWGKorzMupvNhBZsLclsOfTNf6Gp6OO5+Li7G/h0FDZlNMOl7GtX6oIf/hfp0mf1/i7K3X0MUHGMHn4bRmF59wD6796j9B+KxQww7mGVrUup0xWfzywQT2sN81cSAnBdLafVBIVeUzdeTx7TtuutRmIIYZHU6Lodr+A7sccSpVVwBLbCaCSI/oZG4EDqKI8xo8JdgVFwL8/Ey5fKLpqU/GUy+OMI75xExnic5/h9No2URGI=
  - secure: Qnlde+Hl02Ej1NsPr7FXIft9spzDXGwt2O4V2v8PPwSI5QskPSIKvUEQY9Bzae2xzpOtGUeHbIXKJkZ5SXJ1Zz4Ciym8eioPRqwgAcmdZvfYdVVQnqxQiOxW6v6sZmKjS8IVOzzvQRCOqpDPhD5GV1AixrbF0YlF26+3DazTl48o+f4IXUNtcxFaRwtBFRqao4pWQZu+nu3XIc9iM2MmnPpK1K4Pfq0oKIWbaQfmNOxNNC2iC6ZQ+sTTgsmEafPKw88gkrS4i9HwrNaX4Flb9JudijoL/kZcMYHEZ6g2KhVailM6s/kxjeeigqPU6b5NfL1tHRzUWbv0PALth/9LrZrtD9AdTHB6OE1U4NMzAsvTsKz2/tIL7Olm5yFqkJfbLmMtFVQQVOQjR7asgNTUIvah3OqMq28EF77ee0pTI6aR2OR9hlsmVA6l484oVNDETDt+3iA6mSfO3r+oFDkz2jM94n3Ztt55mg4wIR4PX6an2So7nJztYapDrWTxasXzknJenRiv6C25pUVKCCd2P8jchJ+ahstw71tnbtrfGv6w78NccNwW1LoNKfpZnvbwdQ0XFd2V5NfXYHhKeNvoJLxCK18PtWMA2iUb/OYaXNRljNQ9TLNCqo02ltvIi/Bz4sX13UkzMxUez6wtE33q36uU6J5/74rY6AHrEJd6znM=
script:
- echo ${TRAVIS_COMMIT::8}
after_success:
- export BRANCH=$(echo $TRAVIS_BRANCH | sed -e "s,/,_,g;")
- export TAG=$BRANCH-${TRAVIS_COMMIT::8}
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io
- docker pull $REPO
- echo "docker build -t $REPO:$TAG ."
- docker build -t $REPO:$TAG .
- echo "docker push $REPO:$TAG"
- docker push $REPO:$TAG
