language: go
go:
- '1.5'
- '1.6'
services:
- docker
env:
  matrix:
  - REPO=quay.io/wantedly/kong-oauth-token-generator
  global:
  - secure: B57Vp6N52PYmirhiMUWpxSbYHkCumqyX/uy1BQJL0N1D8H+N3sAFM5Qr6u4F6b+bFqDLD2OriyT2PPEsSAiJs+9Xi4xETKSkOP95Iqxea8ZcP0IeW4QCN9Tfs+INWiwkbSCcNoLepFCmYJDLXbB4q/howxMRmHilZe6/hhq+A+kXgSbFeJ7kiPZmD63y0riaE6F86cDiBAmEcoygsk/hBPDB18E/bw0CN2iQLszuMoKsPDTpY1pAc5mn3lMsZqEi6t5NcVIQQha/faQ7VlwvxMHh4PD520hGGvdLWqxJturxMgdh4YDeclup8G7lIcbu0FayXmxBuYIYdV7x/OR5szFMe0JfzRF0xpgOwk0mGgy4JFZvKNNWTJor+dDt9foC2n3Dpmb6zvsXWy5gfJBnN9BtzZzqisYrltFp5InvFVju1Z+6+ykywj4Shq4mIc52u2rL9q2ShtGjsSX0RCTxpr1Cic8EXMn8JTILrIVgrWQ1baGs0unGQISui8YBhcxQDM4mu/dn1DGTDh8m9/oq0hCmrMZxQdlPw8pzK4Hf7u/sOMKMM78l1a/EP99vF8y9oJFpWuosJsCXslwDVrXKTYI5F4mOWksoHovGZWobAOHp+6XOUsVOo0masQg8r4VBwUulfk/lQ9wwYMyY441u+yKsqC8+DLJdOoa/VlfolDs=
  - secure: Q+neMV541tIBh13vL9XQTpFm6ZUkSk2wC5WPkHVcLNo2ZeoiNzhG6KFfWhrgCrHj+p4tsle1UukGVvHcVdpjsOLTSP0OOSCVVXy5wEcWeIZKHHoEs/bJ8a0bjpRAyCF6Z6GR3P9fRY6zCYujFu9auAFb43rlwTrMW6sURatY1emMt0aO2+Z63YUWXH6FIA316qMDdChDvKadhtbJwSId9tbUOVHQBX+8QyWuNUqrCSpd1uchvsw65IyRRq1KM9r4XkYHQ8MUCZ9EUCi9Sl0RK4yUQxDnk0RIHaZ1swRSXPNbYseahdMOrPqijStIWdFLjz0MUNd71Db7y1mdENDTeWsl2cL4RTejXO4OP9sKQtFi15HzDjK0Wqu9vAItVMr+8v4c7GIKkEt5ZlerefFOyvfxEUI9o1BH6tqpOoeSljCku6FAJC6l/TYaYFBUKyhqJ0mwoYCVsQmUok5VhemA08VLJks34ESiM3t+xjbCo3In39EJm+Vh15BrUG0N69R0Hqt/4o6fI52fdXwRP8P1ff0Ge+9qkamDu9E8XLi6xnqa1oanVZu29ueI+j7fqDDnWa48RG1zeSCqD/xjQMstQIqhWZ9IaViccKYAWfpFK2MuIZKdlhNrufp5PGvzNDA1JVsFwDn4TFD/QcPBsx2P3KCGizdms/HoPR7yYUak8pU=
  - secure: JW2cX3YPB00Y6GRi34PuTrJ3ymWPbkQKH3s4opkPfZqzudxQqWlA4JfuJbRAE309uMuuKlNnWDzYYkLz9Ac0qglRbIOzKv0Q2BUvsSJQ8prnVJATm1s6v3tDHejCReV2MPBz3v8P+7MG2uYv6ESLwd5yVcdOEKfOk0rQmGpvtbHlAagrGZcS8UXwm07uxmfj7bGmA1Mfu+zRIwg8dVp/mtu6DxC59DZrPavq9tKuxzdDzjf0EfcvMfKKFZh0CsJVS/mFNxGtehSw8B8LwSkS6Lde2kuQ3DaE9DvJu7vteHOCKy3QtZ996N6ROJ0xYQHgVwUPUtRZRGBkIDV4zCtOX+cLhTR5pfKcsu2plnGXMuay89iz8/C3X2PCSw8fBHEfcvSfIO+yODOJF+b2O7vN3ZJ9QPHoERCHuCtkpof8BdAcTb+t0mL5d9eZU0Ph5NXZllWt2MBg5wRMl/P1rNae9zJ7bDSidasCgi9C2bAJpd4cmxTM+C7Fm9/3D6AG/JNIJNVIhHY9rm2Zeob4k2+aVqF8n5XDluu7Xb1Ga0SVFH3umnI8DzfUajBrMs+hN1Pw9qUkWuYx3X18gH0Vwr6Td91Cl79f3cOESslyg4oYOLweKpBc9g4wCWlClXpcOqouIMopjYVMoyiqS8xOIADVGjH1jLbg+Ul3NrGXIGQR6Z0=
script:
- echo ${TRAVIS_COMMIT::8}
after_success:
- export BRANCH=$(echo $TRAVIS_BRANCH | sed -e "s,/,_,g;")
- export TAG=$BRANCH-${TRAVIS_COMMIT::8}
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io
- docker pull $REPO
- echo "docker build -t $REPO:$TAG ."
- docker build -t $REPO:$TAG .
- echo "docker push $REPO:$TAG"
- docker push $REPO:$TAG
