version: '2'
services:
  kong-database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    ports:
      - 5432
  kong:
    image: mashape/kong:0.9.0
    depends_on:
      - kong-database
    environment:
      - KONG_LOG_LEVEL=notice
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PORT=5432
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=
      - KONG_PG_DATABASE=kong
      - KONG_CLUSTER_LISTEN=0.0.0.0:7946
      - KONG_CLUSTER_ADVERTISE=
      - KONG_CLUSTER_PROFILE=local
      - KONG_DNSMASQ=on
      - KONG_DNSMASQ_PORT=8053
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    security_opt:
      - seccomp:unconfined
    links:
      - kong-database
