version: '2'
services:
  kong-oauth-token-generator:
    image: wantedly/kong-oauth-token-generator
    depends_on:
      - kong
    environment:
      - KONG_HOST=kong
      - KONG_PORT=8001
    ports:
      - 8080
    links:
      - kong
  kong-database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    ports:
      - 5432
  kong:
    image: quay.io/wantedly/kong
    depends_on:
      - kong-database
    environment:
      - DNS_RESOLVER=
      - DNS_IP=
      - DNS_PORT=
      - DNSMASQ_PORT=
      - CLUSTER_IP=
      - CLUSTER_PORT=
      - ADVERTISE_IP=
      - ADBERTISE_PORT=
      - DATABASE=postgres
      - POSTGRES_HOST=
      - POSTGRES_PORT=
      - POSTGRES_DATABASE=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    security_opt:
      - seccomp:unconfined
    links:
      - kong-database
