apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue
  labels:
    name: app
    app: kong-oauth-token-generator
    color: blue
spec:
  imagePullSecrets:
    - name: wantedlybotkey
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: blue
      labels:
        name: app
        app: kong-oauth-token-generator
        color: blue
    spec:
      containers:
      - image: koudaiii/kong-oauth-token-generator:latest
        name: blue
        ports:
          - containerPort: 3000
            name: rails
        env:
          - name: KONG_HOST
            value:
          - name: KONG_PORT
            value:
