apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue
  labels:
    app: kong
    name: oauth-token-generator
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: blue
      labels:
        app: kong
        name: oauth-token-generator
        color: blue
    spec:
      imagePullSecrets:
        - name: wantedlybotkey
      containers:
      - image: quay.io/wantedly/kong-oauth-token-generator:latest
        name: blue
        ports:
          - containerPort: 3000
            name: rails
        env:
          - name: KONG_HOST
            value: kong-internal
          - name: KONG_PORT
            value: "8001"
