apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-frontend
  namespace: kong
  labels:
    app: kong
    name: kong-frontend
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: kong-frontend
      labels:
        app: kong
        name: kong-frontend
    spec:
      imagePullSecrets:
        - name: wantedlybotkey
      containers:
      - image: quay.io/wantedly/kong-frontend:latest
        name: kong-frontend
        ports:
          - containerPort: 8080
            name: go
        env:
          - name: KONG_HOST
            value: kong-internal
          - name: KONG_PORT
            value: "8001"
