apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: green
  labels:
    app: kong
    name: oauth-token-generator
    color: green
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: green
      labels:
        app: kong
        name: oauth-token-generator
        color: green
    spec:
      imagePullSecrets:
        - name: wantedlybotkey
      containers:
      - image: quay.io/wantedly/kong-oauth-token-generator:latest
        name: green
        ports:
          - containerPort: 8080
            name: go
        env:
          - name: KONG_HOST
            value: kong-internal
          - name: KONG_PORT
            value: "8001"
