apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: kong
  labels:
    app: nginx-proxy
spec:
  ports:
    - port: 443
      targetPort: 80
  selector:
    app: nginx-proxy
  type: LoadBalancer
