apiVersion: v1
kind: Service
metadata:
  name: oauth-token-generator
  namespace: kong
  labels:
    app: kong
    name: oauth-token-generator
spec:
  type: LoadBalancer
  ports:
    - name: kong-oauth-token-generator
      port: 443
      targetPort: 8080
  selector:
    app: kong
    name: oauth-token-generator
