apiVersion: v1
kind: Service
metadata:
  name: kong-frontend
  namespace: kong
  labels:
    app: kong
    name: kong-frontend
spec:
  type: LoadBalancer
  ports:
    - name: kong-frontend
      port: 443
      targetPort: 8080
  selector:
    app: kong
    name: kong-frontend
